### PR TITLE
Add Dark Mode Toggle and Enhance Card Styling with Dynamic Text Color

### PR DESCRIPTION
**Pull request by JollyJolli**
This pull request introduces the following enhancements:

- **Dark Mode Toggle:** Added a button to switch between dark mode and light mode. The button, featuring sun and moon icons, is positioned to the right of the search input field.

- **Dynamic Card Styling:** Improved the card generation system to use dynamic text color adjustments. Each card now has a unique color, which is consistently applied even if the page is refreshed. This color is generated based on data from a JSON file, ensuring a persistent and distinctive appearance for each card.

- **File Removal:** Deleted `css/users.css` as the card styles are now generated dynamically through the updated system.

**Changes:**
- Implemented dark mode and light mode styles with persistent user preferences.
- Developed a system to generate cards from JSON data, including dynamic text color adjustments and unique color assignment for each card.
- Removed the redundant `css/users.css` file, consolidating all card styling into the dynamic generation process.

This update enhances the user experience by providing a versatile interface with dynamic styling and ensuring that each card maintains a unique and consistent appearance.

### CODE REVIEW

**Review by narainkarthikv — APPROVED** [review]
Thank you, @JollyJolli! The addition of the dark mode feature is a fantastic improvement. If possible, consider using lighter colors like `lightseagreen`, `lightcoral`, `lightslategrey`, etc... for a more soothing user experience. I'll go ahead and approve this MR. Feel free to make updates to any components in my other repo if you find any bugs or have feature suggestions.

**Comment by JollyJolli** [comment]
@narainkarthikv Hey there! Which other repo?

**Comment by narainkarthikv** [comment]
> @narainkarthikv Hey there! Which other repo?

Check out my `Fit-Track`, `Nmoji`, `Sticky-Memo` repos. If you want to work on an issue or found a bug. Feel free to work on it.

**Comment by JollyJolli** [comment]
Thanks! I will check them

**Pull request merged**
